---
resolver: nightly-2024-03-20

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: f14dca13e3fa06858ee6299333764b9b89d820c9
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/flex-tasks.git
    commit: b50ab20b157f3009835da0206e4bfe8872de6f81
    subdirs:
      - flex-tasks
      - flex-tasks-processing
