---
resolver: nightly-2024-03-20

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: e97c5f06a17c5b99f0bed2a733bfbf974304adf3
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 0e613d15366a2a5e0a2bae34bec2fec5f03575f3
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: fa712df18cba66ce45acfbd3c2a5fbf7ba756dbb
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - diagrams-graphviz-1.4.1.1@sha256:9a2bf7b7c9c86ab28228d36017c70cf1b53c95dae4004fc71e81fbc702098e9f,1495

