---
resolver: lts-20.26

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: dbc0713b6b8da7d1305bbfbd4d6856a78676e1e1
    subdirs:
      - output-blocks
