---
resolver: nightly-2025-10-07

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: 2960bddfed612333a0f631aaf9be483883c72718
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/flex-tasks.git
    commit: cb17569e668ea839991b657a1d82840584cdb88d
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: 8067088f23759d787c049677a26868df26c1676f
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - diagrams-graphviz-1.4.1.1@sha256:9a2bf7b7c9c86ab28228d36017c70cf1b53c95dae4004fc71e81fbc702098e9f,1495
  - git: https://git.uni-due.de/fmi/autotool-dev
    commit: 56e75cd74d44f81ae52baa3b886025bd4d158bbb
    subdirs:
      - base
      - data
      - reader
      - todoc
      - transport
      - util
