---
resolver: lts-20.26

packages:
  - .
allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-monad.git
    commit: 1f3edf2cd4a13ca6cb62e24a57f6da66ef6894d0
    subdirs:
      - output-monad
