---
resolver: nightly-2024-03-20

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: 77dd77fcbb8084a31c6633089605f7654af12ece
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 69c3cc80397a6cd8a462608dd668a352e48104dc
    subdirs:
      - flex-tasks
      - flex-tasks-processing
