---
resolver: lts-20.26

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: d596175381844ce23c01e3fbe11e6f960e243d57
    subdirs:
      - output-blocks
