---
resolver: nightly-2024-03-20

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: 77d9867b1d872795064086836e1b0cf24bcfd296
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 85dc107fc122348bf63d5238a4a4f2f4fd9ec337
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: 8067088f23759d787c049677a26868df26c1676f
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - diagrams-graphviz-1.4.1.1@sha256:9a2bf7b7c9c86ab28228d36017c70cf1b53c95dae4004fc71e81fbc702098e9f,1495
