---
resolver: nightly-2024-03-20

packages:
  - .
  - examples

allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: 77dd77fcbb8084a31c6633089605f7654af12ece
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 26c7fe304007e78f669519bb62ae374cc85281a9
    subdirs:
      - flex-tasks
      - flex-tasks-processing
