---
name: haskell-template-setup
version: 0.1.0.0

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - autotool-capabilities
  - autotool-capabilities-io-instances
  - base >= 4.7 && < 5
  - flex-tasks
  - logic-tasks
  - output-blocks
  - parsec
  - string-interpolate
  - syb
  - yesod-form
library:
  source-dirs: .
